version: "3"
services:
  web:
    image: passlessauth/python
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www
    command: sh -c "cp -n .env.example .env && python run.py"
    volumes:
      - .:/var/www
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - ${PYTHON_EXPOSE_PORT}:5000
    depends_on:
    - db
  db:
    image: mysql:5.7.24
    restart: always
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_SERVER: ${MYSQL_SERVER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}